trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: mirror-git-repository-vsts-task@1
    inputs:
      sourceGitRepositoryUri: '$(Build.Repository.Uri)'
      sourceGitRepositoryPersonalAccessToken: '$(AZURE)'
      destinationGitRepositoryUri: 'https://github.com/leap-spark/docker-wordpress'
      destinationGitRepositoryPersonalAccessToken: '$(GITHUB)'
